kind = "mobile"
previewPath = "/passport-ocr-mobile/"
title = "Passport OCR Mobile"
version = "1.0.0"
id = "artifacts/passport-ocr-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/passport-ocr-mobile/" ]
localPort = 26150

[services.development]
run = "pnpm --filter @workspace/passport-ocr-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/passport-ocr-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/passport-ocr-mobile", "run", "serve" ]

[services.env]
PORT = "26150"
BASE_PATH = "/passport-ocr-mobile/"
